/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.QuanLy;

/**
 *
 * @author NHT_Kurumi
 */
public class jp_QuanLy extends javax.swing.JPanel {

    jp_QuanLyBan ban;
    jp_QuanLyThucDon thucdon;
    jp_QuanLyNhanVien nhanvien;
    jp_QuanLyTaiKhoan taikhoan;

    public jp_QuanLy() {
        initComponents();
        reloadPanel(1);
    }

    private void reloadPanel(int i) {
        jpQuanLy.removeAll();
        switch (i) {
            case 1:
                if (thucdon == null) {
                    thucdon = new jp_QuanLyThucDon();
                } 
                jpQuanLy.add(thucdon);
                break;
            case 2:
                if (ban == null) {
                    ban = new jp_QuanLyBan();
                }
                jpQuanLy.add(ban);
                break;
            case 3:
                if(nhanvien == null){
                    nhanvien = new jp_QuanLyNhanVien();
                }
                jpQuanLy.add(nhanvien);
                break;
            case 4:
                if(taikhoan == null){
                    taikhoan = new jp_QuanLyTaiKhoan();
                }
                jpQuanLy.add(taikhoan);
                break;
            default:
                break;
        }
        jpQuanLy.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btThucDon = new javax.swing.JButton();
        btBan = new javax.swing.JButton();
        btNhanVien = new javax.swing.JButton();
        btTaiKhoan = new javax.swing.JButton();
        jpQuanLy = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mục quản lý", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        btThucDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btThucDon.setText("Quản lý thực đơn");
        btThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThucDonActionPerformed(evt);
            }
        });

        btBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btBan.setText("Quản lý bàn");
        btBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanActionPerformed(evt);
            }
        });

        btNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btNhanVien.setText("Quản lý nhân viên");
        btNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienActionPerformed(evt);
            }
        });

        btTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btTaiKhoan.setText("Quản lý tài khoản");
        btTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThucDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(btNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(btTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );

        jpQuanLy.setBackground(new java.awt.Color(255, 255, 255));
        jpQuanLy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jpQuanLy.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanActionPerformed
        reloadPanel(2);
    }//GEN-LAST:event_btBanActionPerformed

    private void btThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThucDonActionPerformed
        reloadPanel(1);
    }//GEN-LAST:event_btThucDonActionPerformed

    private void btNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienActionPerformed
        reloadPanel(3);
    }//GEN-LAST:event_btNhanVienActionPerformed

    private void btTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaiKhoanActionPerformed
        reloadPanel(4);
    }//GEN-LAST:event_btTaiKhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBan;
    private javax.swing.JButton btNhanVien;
    private javax.swing.JButton btTaiKhoan;
    private javax.swing.JButton btThucDon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpQuanLy;
    // End of variables declaration//GEN-END:variables
}
